version: '3'
services:

  # THE APPLICATION
  app:
    #build:
      #context: .
      #dockerfile: .docker/app.dockerfile
    image: semanticeffect/php-7.1-alpine-xdebug
    container_name: app
    links:
      - database
      - redis
    expose:
      - 9000

# THE WEB SERVER
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    container_name: web
    links:
      - app
    expose:
      - 80

  # THE DATABASE
  database:
    image: mysql:5.7
    container_name: database
    expose:
      - 3306
    ports:
      - 33063:3306

  # THE CACHE
  redis:
    image: redis:4.0-alpine
    container_name: redis
    ports:
      - 63791:6379

volumes:
  app:
