version: '3'

services:
  # THE APPLICATION
  app:
    volumes:
      - ../docker_test:/var/www
    env_file:
      - docker.env

  # THE WEB SERVER
  web:
    volumes:
      - ../docker_test:/var/www
    env_file:
      - docker.env
    networks:
      - default
      - nginx-proxy

  # THE DATABASE
  database:
    volumes:
      - project_dbdata:/var/lib/mysql
    env_file:
      - docker.env

networks:
  nginx-proxy:
      external: true
      name: nginx-proxy

volumes:
  project_dbdata:

