version: '3'

services:

# THE WEB SERVER
  web:
    env_file:
      - docker.env
    networks:
      - default
      - nginx-proxy

  database:
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

volumes:
  dbdata:

